-- @version 3.0.0
-- @author Daniel Lumertz, Mavriq
-- @provides
--    [main] Receive Sockets Demo.lua
--    [main] Send Sockets Demo.lua
--    [main] Test with Luasocket functions.lua
--    [nomain] socket module/socket/core.dll
--    [nomain] socket module/socket/core.so
--    [nomain] socket module/socket/core.so.linux
--    [nomain] socket module/*.lua
-- @changelog
--    + Update the osc functions to a osc module
--    + Update the examples to use the modules
--    + New function to encode/decode osc
--    + New function to iterate osc/udp

