--local VSDEBUG = dofile("c:/Users/danie/.vscode/extensions/antoinebalaine.reascript-docs-0.1.16/debugger/LoadDebug.lua")
-- @version 1.8.1
-- @author Daniel Lumertz
-- @provides
--    [nomain] General Functions.lua
--    [nomain] presets.lua
--    [nomain] GUI Functions.lua
--    [nomain] groups.lua
--    [nomain] Item Sampler Settings Management.lua
--    [nomain] REAPER Functions.lua
--    [nomain] Sequencer Item.lua
--    [nomain] utils/*.lua
--    [nomain] DL Functions/*.lua
--    [main] Item Simpler.lua
-- @changelog
--    + Add option that activated sequencers follow item/track selection.
--    + Add Group Grid Editor. Including options to set the range of each group. Clicking sets group to a certain note. Shift-click extends the range up to certain note. Ctrl-click to change the untransposed pitch.  
--    + Add action to create groups in batches, using selected items/tracks as sources. Action found by right clicking the '+' menu
--    + Add usersetting to remap MIDI note names using group names.
--    + Add usersetting "Activated Sequencer Follow Selection"
--    + Add right click contexts to copy/paste multiple settings (right-clicking an source at the drop-down or an Setting tree  node)
--    + Add action to untag selected items that were generated by Item Sampler. Untagged items wont be deleted in newer generations.
--    + Add action to duplicate a group.
--    + Add Stretch Option.
--    + Restylized the UI. Changed colors, font is more compact, removed the older group editor.
--    + Bug Fix: Fixed renaming/deleting groups. It was not saving and was scrambling the groups after user action
--    + Bug Fix: Using ipairs to properlly shows groups in the correct order 
--    + Bug Fix: Prevent pasting a group setting if none have been copied.
--    + Bug Fix: Removed debug line
--    + Bug Fix: Deleting source items


--TODOs
-- Update header require

local version = '1.8.1'
local info = debug.getinfo(1, 'S');
local script_path = info.source:match[[^@?(.*[\/])[^\/]-$]]

package.path = package.path  .. ';' ..  reaper.ImGui_GetBuiltinPath() .. '/?.lua'
ImGui = require 'imgui' '0.10'
ctx = ImGui.CreateContext('daniellumertz_Item Sampler')

--local demo = require 'ReaImGui_Demo'

-- Main Tables
local ProjTable = {
}
ExtStates = {
    ext_name = 'daniellumertz_Item Sampler',
    sequencers = {
        key = 'SequencerSettings'
    },
    pasted = {
        seq_key = 'PastedSequencer', -- value is the Sequencer item/track GUID  
        group_key = 'PastedGroup'-- value is the group GUID  
    },
    user_settings = {
        key = 'UserSettings' 
    }
}

local save_mt = { -- if is_save[1] then save end
    __newindex = function(tbl, key, value)
        if value then
            rawset(tbl, 1, true)
        end
        -- if value is false, do nothing at all
    end
}

GUI = {
    stretch = {
        min = 0.01
    },
    groups_popup = {
        was_open = false
    },
    create_popup = {
        label = 'create_popup',
        name = 'Create Groups',
        source = {
            is_item = 0 -- 0 item, 1 track
        },
        groups = {
            is_one = 1,
            settings = 0,
            range = {
                set_by_key = true,
                start_pitch = 60
            },
            is_replacing = false
        }
    },
    copies = {}, -- Where it store something that is copied ex: Gui.copies.targets = targets table 
    is_save = setmetatable({}, save_mt),
    is_save_us = setmetatable({}, save_mt), -- User settings!
    sequencers = {
        draw_window = {
            arrange_win = reaper.JS_Window_FindChildByID(reaper.GetMainHwnd(), 0x3E8),
            arrange = {
            },
            flags = 
                ImGui.WindowFlags_NoBackground      |
                ImGui.WindowFlags_NoTitleBar        |
                ImGui.WindowFlags_NoResize          |
                ImGui.WindowFlags_NoMove            |
                ImGui.WindowFlags_NoScrollbar       |
                ImGui.WindowFlags_NoScrollWithMouse |
                ImGui.WindowFlags_NoCollapse        |
                ImGui.WindowFlags_NoSavedSettings   |
                ImGui.WindowFlags_NoFocusOnAppearing|
                ImGui.WindowFlags_NoNav             |
                ImGui.WindowFlags_NoDecoration      |
                ImGui.WindowFlags_NoInputs -- mouse clicks pass through
        }
    },
    grid_editor = {
        accidents = {[1]=true, [3]=true, [6]=true, [8]=true, [10]=true},
        first_run = true
    }
}

--- Loading
dofile(script_path .. 'General Functions.lua') -- General Functions needed
dofile(script_path .. 'GUI Functions.lua') -- General Functions needed
dofile(script_path .. 'groups.lua') -- General Functions needed
dofile(script_path .. 'presets.lua') -- General Functions needed
dofile(script_path .. 'REAPER Functions.lua') -- preset to work with Tables
require('DL Functions.Serialize')
require('DL Functions.REAPER Items')
require('DL Functions.REAPER Enumerate')
require('DL Functions.General Table')
require('DL Functions.ImGui')
require('DL Functions.General Number')
local is = require('Sequencer Item')
local config = require('Item Sampler Settings Management')

if not CheckSWS() or not CheckReaImGUI() or not CheckJS() then return end
-- Imgui shims to 0.7.2 (added after the news at 0.8)
--dofile(reaper.GetResourcePath() .. '/Scripts/ReaTeam Extensions/API/imgui.lua')('0.7.2')


--- Load User Settings

UserSettings = config.Load(ExtStates.ext_name, ExtStates.user_settings.key) or config.default(version)
local is_change
UserSettings, is_change = config.Update(UserSettings)
if is_change then -- Some update happended
    config.Save(ExtStates.ext_name, ExtStates.user_settings.key, UserSettings)
end

--- Load Functions


function ListItems()
    local list = {}
    local count = reaper.CountSelectedMediaItems(0)
    for i = 0, count do
        local loop_item = reaper.GetSelectedMediaItem(0, i)
        table.insert(list, loop_item)
    end
    return list
end

function ListTracks(proj)
    local t = {}
    local count = reaper.CountSelectedTracks2(proj, false)
    for i = 0, count -1 do
        local track = reaper.GetSelectedTrack2(proj, i, false)
        t[#t+1] = track
    end
    return t
end

function IsItemPastedFromSequencer(item)
    -- Set Ext State
    local  retval, chunk = DL.item.GetExtState(item, ExtStates.ext_name, ExtStates.pasted.seq_key)
    return not (chunk == ''), chunk    
end

function CheckGroups(sequencers) -- Return false if fails tests; return list similar to groups if pass all tests and make track sources into items
    for k, sequencer in DL.t.ipairs_reverse(sequencers) do
        local proceed = false
        -- Main Sequencer 
        if not sequencer.seq then -- Probably wont happen as I am checking for the sequencer item/track every loop before this function 
            print('Sequencer Item/Track Missing!')
            table.remove(sequencers, k)
            return false
        end
        -- Solve the sequencer (will remove after pasting)
        sequencer.sequencers_solved = {}
        if sequencer.is_item then
            sequencer.sequencers_solved[#sequencer.sequencers_solved+1] = sequencer.seq
        else
            for item in DL.enum.TrackMediaItem(sequencer.seq) do
                if not IsItemPastedFromSequencer(item) then
                    local take = reaper.GetActiveTake(item)
                    if reaper.BR_IsTakeMidi(take) then
                        sequencer.sequencers_solved[#sequencer.sequencers_solved+1] = item
                    end
                end
            end

            if #sequencer.sequencers_solved == 0 then
                print('No sequencer item found!')
                return false
            end
        end

        -- Add Temporary seq guid to the sequencer table (used when cleaning items and when pasting with ext state of the guid)
        local f = (sequencer.is_item and reaper.GetSetMediaItemInfo_String) or reaper.GetSetMediaTrackInfo_String
        local _, s_guid = f(sequencer.seq, 'GUID', '', false)
        sequencer.s_guid = s_guid 
        
        -- Groups
        local groups = sequencer.groups
        for i, group in ipairs(groups) do
            group.Check = true -- true unless it fails a check
            -- Is Selected?
            if group.Selected == false then 
                goto continue
            end

            -- List Sequence
            if not group.list_sequence or #group.list_sequence == 0 then
                group.Check = false
                print('No Sources at Group '..group.name)
                goto continue
            end
            -- Make a temporary copy of List Sequence (substitute all tracks by its items)
            group.list_sources_solved = {}
            for si, source in DL.t.ipairs_reverse(group.list_sequence) do -- list_sequence are the sources 
                local is_item = reaper.ValidatePtr(source, 'MediaItem*')
                local is_track =  reaper.ValidatePtr(source, 'MediaTrack*')

                if is_item then
                    table.insert(group.list_sources_solved , source)
                elseif is_track then -- Transform tracks in items
                    local track = source
                    for item in DL.enum.TrackMediaItem(track) do
                        -- Sources cant be created from Item Sampler
                        if not IsItemPastedFromSequencer(item) then 
                            table.insert(group.list_sources_solved, item)
                        end
                    end
                else
                    print('The Source #'..si..', from the group #' ..group.name..', was not found on your project.')
                    print('Removing this Source!')
                    table.remove(group.list_sequence, si)
                end
            end

            -- Check if any valid sequence
            if #group.list_sources_solved == 0 then
                group.Check = false
                print('No Valid Source at Group '..group.name)
            end

            -- Check for Targets Tracks
            if group.Targets then
                for ti, target in DL.t.ipairs_reverse(group.Targets) do
                    if not reaper.ValidatePtr(target, 'MediaTrack*') then
                        print('At group '..group.name..' target track #'..ti..'was not found! Removing target track!')
                        table.remove(group[i].Targets, ti)
                    end
                end

                if #group.Targets == 0 then
                    group.Targets = nil
                end
            end
            proceed = true -- someone passed, something will be pasted
            ::continue::
        end
        sequencer.proceed = proceed
    end
    return true
end


function UntagSelectedItems(proj)
    for item in DL.enum.SelectedMediaItem(proj) do
        local _, s_guid = DL.item.GetExtState(item, ExtStates.ext_name, ExtStates.pasted.seq_key)
        if s_guid ~= '' then
            DL.item.SetExtState(item, ExtStates.ext_name, ExtStates.pasted.seq_key, '')
        end
    end
end

-- If the pasted item found is in an open sequencer:
    -- If it is from a deleted group
        -- deleted
    -- if it is from an active/disabled(indiferent) group and their Settings.Erase = true
        -- deleted
    -- else keep it
function CleanAreas(proj, sequencers)
    local sequencers_guided = {} -- to save resources make a similar table organized by guid 
    for si, sequencer in ipairs(sequencers) do
        local s_guid = sequencer.s_guid
        sequencers_guided[s_guid] = {}
        for gi, group in ipairs(sequencer.groups) do
            local g_guid = group.Settings.GUID 
            sequencers_guided[s_guid][g_guid] = group.Settings.Erase and  group.Selected
        end
    end
    for track in DL.enum.Tracks(proj) do
        local cnt = reaper.CountTrackMediaItems(track)
        for iidx = cnt-1, 0, -1 do
            local item = reaper.GetTrackMediaItem(track, iidx)
            local _, s_guid = DL.item.GetExtState(item, ExtStates.ext_name, ExtStates.pasted.seq_key)
            if s_guid ~= '' and sequencers_guided[s_guid] then -- found a pasted item from an active sequencer
                local _, g_guid = DL.item.GetExtState(item, ExtStates.ext_name, ExtStates.pasted.group_key)
                if (sequencers_guided[s_guid][g_guid] == nil) or (sequencers_guided[s_guid][g_guid]) then -- from an deleted group or from an Settings.Erase group 
                    reaper.DeleteTrackMediaItem(track, item)
                end
            end
        end
    end 
end

function ChangeVolume(pasted_item, vel, Vel_OriginalVal, Vel_Min, Vel_Max)
    local vol_before = reaper.GetMediaItemInfo_Value(pasted_item, 'D_VOL' )
    local delta
    if vel < Vel_OriginalVal then
        delta = scale(vel,1,Vel_OriginalVal,Vel_Min,0) -- Scale vel (1 to Vel_Original)"MIDI" to (delta Settings.Vel_Min, 0)
    elseif vel > Vel_OriginalVal then
        delta = scale(vel,Vel_OriginalVal,127,0,Vel_Max) -- Scale vel (Vel_Original to 127)"MIDI" to (delta Settings.Vel_Min, 0)
    else -- vel == Vel_OriginalVal
        return
    end
    local new_val = AddDBinLinear(vol_before, delta)
    reaper.SetMediaItemInfo_Value( pasted_item, 'D_VOL',new_val)
end


function ChangePitch(pasted_item, pitch, Pitch_Original)
    local item_take = reaper.GetMediaItemTake(pasted_item, 0)
    local pitch_before = reaper.GetMediaItemTakeInfo_Value( item_take, 'D_PITCH' )
    local delta = pitch - Pitch_Original
    reaper.SetMediaItemTakeInfo_Value( item_take, 'D_PITCH', delta + pitch_before )    
end

function PlaceSequenceInGroups(proj, sequencers, is_random,sequence_reverse,isrand_sequence)
    -- Check 
    local proceed = CheckGroups(sequencers)
    if not proceed then 
        print('Nothing to be pasted!')
        return false 
    end
    -- Paste
    reaper.PreventUIRefresh(1)
    reaper.Undo_BeginBlock()
        --Save Info
    local selected_items = SaveSelectedItems()
    local selected_tracks = SaveSelectedTracks()

    CleanAreas(proj, sequencers) 
    for si, sequencer in ipairs(sequencers) do
        if sequencer.proceed then
            local groups = sequencer.groups
            for gi, group in pairs(groups) do
                if group.Selected and group.list_sources_solved and #group.list_sources_solved > 0 then
                    Place_Sequence(group, sequencer, is_random,sequence_reverse,isrand_sequence) -- (is_random,sequence_reverse,isrand_sequence)
                end
            end
        end
        sequencer.proceed = nil
        sequencer.sequencers_solved = nil
    end 

    --Reset Things back
    LoadSelectedItems(selected_items)
    LoadSelectedTracks(selected_tracks)

    reaper.Undo_EndBlock2(0, 'Item Sampler: Place Sequence', -1)
    reaper.PreventUIRefresh(-1)
    
end



function Place_Sequence(group, sequencer, is_random,sequence_reverse,isrand_sequence)
    local Settings = group.Settings
    --- Use the solved tables
    local seq_items = sequencer.sequencers_solved
    local list_sequence = group.list_sources_solved
    group.list_sources_solved = nil -- not necessary to keep it after this function

    -- Paste
    local not_used
    if is_random == true and isrand_sequence == true then
        not_used = {}
        for i = 1, #list_sequence do
            not_used[i] = i
        end
    end
    local counter = 0
    for k, seq in ipairs(seq_items) do
        local item_take = reaper.GetMediaItemTake(seq, 0)
        local seq_start = reaper.GetMediaItemInfo_Value(seq, 'D_POSITION')
        local seq_len = reaper.GetMediaItemInfo_Value(seq, 'D_LENGTH')
        local seq_fim = seq_start + seq_len
        local retval, notecnt, ccevtcnt, textsyxevtcnt = reaper.MIDI_CountEvts(item_take)
        for idx_note = 0, notecnt-1 do
            local retval, selected, muted, startppqpos, endppqpos, chan, pitch, vel = reaper.MIDI_GetNote( item_take, idx_note )
            
            -- Range
            if pitch > Settings.NoteRange.Max or pitch < Settings.NoteRange.Min then 
                goto continue 
            end
            if vel > Settings.VelocityRange.Max or pitch < Settings.VelocityRange.Min then 
                goto continue 
            end
            ----
            local note_start = reaper.MIDI_GetProjTimeFromPPQPos(item_take, startppqpos)
            local note_end = reaper.MIDI_GetProjTimeFromPPQPos(item_take, endppqpos)
            if seq_start > note_start and seq_start >= note_end then
                goto continue
            elseif seq_start > note_start then -- note before and after start of item
                note_start = seq_start
            elseif note_start < seq_fim and note_end > seq_fim then
                note_end = seq_fim
            elseif note_start > seq_fim then
                goto continue
            end 

            -- Choose Item
            local list_idx = 0
            if is_random then
                if not isrand_sequence then -- Choose random can repeat 
                    list_idx = math.random(#list_sequence)
                else -- Choose random whitout repeating till start again
                    local rand_num = math.random(#list_sequence-(#list_sequence-#not_used))
                    list_idx = not_used[rand_num]
                    table.remove(not_used, rand_num) 
                    if #not_used == 0 then  --reset not_used list when full
                        for i = 1, #list_sequence do
                            not_used[i] = i
                        end
                    end
                end
            else
                -- Get item list idx
                if sequence_reverse == false then
                    list_idx = (counter%#list_sequence)+1
                else
                    list_idx = #list_sequence - (counter%#list_sequence)
                end
            end

            --  Copy 
            local paste_track 
            if not Settings.Targets or #Settings.Targets == 0 then
                paste_track = reaper.GetMediaItemTrack(list_sequence[list_idx])
            else
                paste_track = Settings.Targets[math.random(#Settings.Targets)]
            end
            local pasted_item = CopyMediaItemToTrack(list_sequence[list_idx], paste_track, note_start )

            -- Set Volume Items 
            if Settings.Velocity == true then
                ChangeVolume(pasted_item, vel, Settings.Vel_OriginalVal,Settings.Vel_Min,Settings.Vel_Max)
            end
            
            -- Set Pitch 
            if Settings.Pitch == true then
                ChangePitch(pasted_item, pitch, Settings.Pitch_Original)
            end            
            
            -- Set Stretch
            if Settings.stretch.is_stretch then
                local apply_stretch = 1 -- 1 is no stretch, it is multiplying
                if vel < Settings.stretch.original_stretch then
                    apply_stretch = scale_log(vel,1,Settings.stretch.original_stretch,Settings.stretch.min_stretch, 1) 
                elseif vel > Settings.stretch.original_stretch then
                    apply_stretch = scale_log(vel, Settings.stretch.original_stretch, 127, 1, Settings.stretch.max_stretch) 
                end
                for pasted_take in DL.enum.Takes(pasted_item) do
                    local original_stretch = reaper.GetMediaItemTakeInfo_Value(pasted_take, 'D_PLAYRATE')
                    local new_stretch = apply_stretch * original_stretch
                    reaper.SetMediaItemTakeInfo_Value(pasted_take, 'D_PLAYRATE', new_stretch)      
                end
                -- Stretch length
                local original_len = reaper.GetMediaItemInfo_Value(pasted_item, 'D_LENGTH')
                local new_len = original_len / apply_stretch
                reaper.SetMediaItemInfo_Value(pasted_item, 'D_LENGTH', new_len)
            end

            -- Trim Item
            TrimItem(Settings, pasted_item, seq, idx_note, notecnt, item_take, endppqpos )

            -- Set Ext State
            DL.item.SetExtState(pasted_item, ExtStates.ext_name, ExtStates.pasted.group_key, group.Settings.GUID)
            DL.item.SetExtState(pasted_item, ExtStates.ext_name, ExtStates.pasted.seq_key, sequencer.s_guid)

            counter = counter + 1
            ::continue::
        end
    end
end

------ Gui Func
function HSV(h, s, v, a)
    local r, g, b = ImGui.ColorConvertHSVtoRGB(h, s, v)
    return ImGui.ColorConvertDouble4ToU32(r, g, b, a or 1.0)
end

function ChangeColor(H,S,V,A)
    --ImGui.PushID(ctx, '')
    local button = HSV( H, S, V, A)
    local hover =  HSV( H, S , (V+0.2 < 1) and V+0.2 or 1 , A)
    local active = HSV( H, S, (V+0.3 < 1) and V+0.3 or 1 , A)
    ImGui.PushStyleColor(ctx, ImGui.Col_Button,  button)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonHovered, hover)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonActive,  active)
end

function ChangeColorButton(H,S,V,A)
    local button = HSV( H, S, V, A)
    local hover =  HSV( H, S , (V+0.2 < 1) and V+0.2 or 1 , A)
    local active = HSV( H, S, (V+0.3 < 1) and V+0.3 or 1 , A)
    ImGui.PushStyleColor(ctx, ImGui.Col_Button,  button)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonHovered, hover)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonActive,  active)
end

function ToolTip(text)
    if ImGui.IsItemHovered(ctx) then
        if ImGui.BeginTooltip(ctx) then
            ImGui.PushTextWrapPos(ctx, ImGui.GetFontSize(ctx) * 35.0)
            ImGui.PushTextWrapPos(ctx, 200)
            ImGui.Text(ctx, text)
            ImGui.PopTextWrapPos(ctx)
            ImGui.EndTooltip(ctx)
        end
    end
end

CounterStyle = 0 -- to undo Styles


function ResetStyleCount()
    ImGui.PopStyleColor(ctx,CounterStyle) -- Reset The Styles (NEED FOR IMGUI TO WORK)
    CounterStyle = 0
end

function ChangeColorTab(H,S,V,A)
    local button = HSV( H, S, V, A)
    local act_hover =  HSV( H, S + 0.3 , (V+0.4 < 1) and V+0.4 or 1 , A)
    ImGui.PushStyleColor(ctx, ImGui.Col_Tab,  button)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabHovered, act_hover)
    ImGui.PushStyleColor(ctx,  ImGui.Col_TabSelected,  act_hover)
    ImGui.PushStyleColor(ctx,  ImGui.Col_TabSelectedOverline,  button) 
    CounterStyle = CounterStyle + 4
end


-- GUI init
function GuiInit()
    ctx = ImGui.CreateContext('Item Sequencer',ImGui.ConfigFlags_DockingEnable) -- Add VERSION TODO
    FONT = ImGui.CreateFont('sans-serif', 15) -- Create the fonts you need
end

function CheckProjChange(ProjTable, UserSettings) 
    local current_proj = reaper.EnumProjects(-1)
    if (not OldProj) or (OldProj ~= current_proj)  then  -- Not First run or project changed
        ProjTable[current_proj] = ProjTable[current_proj] or {}
    end 

    local cnt = reaper.GetProjectStateChangeCount(current_proj)
    if ProjTable[current_proj].change_cnt ~= cnt then
        local action = reaper.Undo_CanRedo2( current_proj )
        if ProjTable[current_proj].Sequencers and action and string.match(action, 'Item Sampler:') then
            is.ReopenSequencers(current_proj, ProjTable[current_proj].Sequencers, version)
        end
        -- 
        if UserSettings.activate.follow_selection then
            local selected_sequencers = {}
            for track in DL.enum.SelectedTracks2(current_proj, false) do
                local bol, ext = reaper.GetSetMediaTrackInfo_String(track, string.format('P_EXT:%s : %s', ExtStates.ext_name, ExtStates.sequencers.key), '', false)
                if ext ~= '' then
                    selected_sequencers[#selected_sequencers+1] = {is_item = false, seq = track}
                end
            end 

            for item in DL.enum.SelectedMediaItem(current_proj) do
                local bol, ext = DL.item.GetExtState(item, ExtStates.ext_name, ExtStates.sequencers.key)
                if ext ~= '' then
                    selected_sequencers[#selected_sequencers+1] = {is_item = true, seq = item}
                end
            end
            
            if #selected_sequencers > 0 then
                ProjTable[current_proj].Sequencers = {}
                local sequencers = ProjTable[current_proj].Sequencers

                for k, sequencer in ipairs(selected_sequencers) do
                    sequencers[#sequencers+1] = is.OpenSequencer(current_proj, sequencer.seq, sequencer.is_item, version)
                end

                sequencers.focus = 1
            end
        end
        ProjTable[current_proj].change_cnt = cnt
    end
    OldProj = current_proj    
    return current_proj, ProjTable
end

function CopyPasteContext(copy_id, t)
    if ImGui.BeginPopupContextItem(ctx) then
        if ImGui.Button(ctx, 'Copy Settings', 125) then
            GUI.copies[copy_id] = table_copy(t)[copy_id]
        end

        if GUI.copies[copy_id] and ImGui.Button(ctx, 'Paste Settings', 125) then
            t[copy_id] = GUI.copies[copy_id]
            GUI.is_save.check = true
        end
        ImGui.EndPopup(ctx)
    end
end

function CopyPasteSequencerSettings(st)
    if ImGui.BeginPopupContextItem(ctx) then
        if ImGui.Button(ctx, 'Copy Settings', 125) then
            GUI.copies['sequencer'] = table_copy(st)
        end
    
        if GUI.copies['sequencer'] and ImGui.Button(ctx, 'Paste Settings', 125) then
            st.groups = GUI.copies['sequencer'].groups -- The only thing that needs to be copied over, the rest is sequencer specific.
            GUI.is_save.check = true
        end
        ImGui.EndPopup(ctx)
    end
end

 

function loop()


    local proj = CheckProjChange(ProjTable, UserSettings)
    PushStyle(ctx)
    --demo.PushStyle(ctx)
    --demo.ShowDemoWindow(ctx)
    if not PreventPassKeys2 then -- Passthrough keys
        DL.imgui.SWSPassKeys(ctx, false)
    end
    Ctrl, Shift, Alt = GetModKeys()

    local _
    local window_flags = ImGui.WindowFlags_MenuBar | ImGui.WindowFlags_NoNav | ImGui.WindowFlags_TopMost 

    ImGui.SetNextWindowSize(ctx, 425, 925, ImGui.Cond_Once)-- Set the size of the windows.  Use in the 4th argument ImGui.Cond_FirstUseEver() to just apply at the first user run, so ImGUI remembers user resize s2
    
    ImGui.PushFont(ctx, FONT, 14)

    if SetDock then
        ImGui.SetNextWindowDockID(ctx, SetDock)
        if SetDock== 0 then
            ImGui.SetNextWindowSize(ctx, 300, 700)
        end
        SetDock = nil
    end

    local visible, open  = ImGui.Begin(ctx, 'Item Sampler ' ..version, true, window_flags)


    local gui_w , gui_h = ImGui.GetContentRegionAvail(ctx)
    local gui_x, gui_y = ImGui.GetWindowPos(ctx)

    --- GUI HERE

    if visible then
        --------- Menu Bar
        if ImGui.BeginMenuBar(ctx) then
            if ImGui.BeginMenu(ctx, 'Options') then
                if ImGui.MenuItem(ctx, 'Show Tool Tips', nil, UserSettings.tips) then
                    UserSettings.tips = not UserSettings.tips
                    GUI.is_save_us.check = true
                end

                if ImGui.MenuItem(ctx, 'Reset Settings') then
                    UserSettings = config.default(version)
                    GUI.is_save_us.check = true
                end

                if ImGui.MenuItem(ctx, 'Activated Sequencer Follows Selection', nil, UserSettings.activate.follow_selection) then
                    UserSettings.activate.follow_selection = not UserSettings.activate.follow_selection
                    GUI.is_save_us.check = true
                end

                if ImGui.MenuItem(ctx, 'MIDI Note Names Follow Group Names', nil, UserSettings.sequencers.rename_note_names) then
                    UserSettings.sequencers.rename_note_names = not UserSettings.sequencers.rename_note_names
                    -- Cleans or update the note names
                    for proj_loop, pt in pairs(ProjTable) do
                        for si, st in ipairs(pt.Sequencers) do
                            if UserSettings.sequencers.rename_note_names then 
                                is.RenameMIDINotes(proj_loop, st)
                            else
                                is.UnameMIDINotes(proj, st)
                            end
                        end
                    end
                    GUI.is_save_us.check = true
                end

                ImGui.Separator(ctx)

                if ImGui.MenuItem(ctx, 'Draw Over Items/Tracks', "", UserSettings.gui.draw.active.is_draw) then
                    UserSettings.gui.draw.active.is_draw = not UserSettings.gui.draw.active.is_draw
                    GUI.is_save_us.check = true
                end
                if UserSettings.gui.draw.active.is_draw then
                    if ImGui.BeginMenu(ctx, 'Draw Options') then
                        local dmenu = {
                            {
                                text = 'Focused Sequencers:',
                                configs = UserSettings.gui.draw.focused
                            },
                            {
                                text = 'Active Sequencers:',
                                configs = UserSettings.gui.draw.active
                            },
                            {
                                text = 'Target Tracks:',
                                configs = UserSettings.gui.draw.target_tracks
                            },
                            {
                                text = 'Sources:',
                                configs = UserSettings.gui.draw.sources
                            },
                        }
                        for k, menu in ipairs(dmenu) do
                            ImGui.Text(ctx, menu.text)
                            local change
                            if not menu.configs.is_multicolor then
                                GUI.is_save_us.check, menu.configs.color = ImGui.ColorEdit4(ctx, '##color' .. k,
                                    menu.configs.color, ImGui.ColorEditFlags_NoInputs)
                            end
                            ImGui.SameLine(ctx)
                            --change, menu.configs.is_multicolor = ImGui.Checkbox(ctx, 'Use Multi-Color##'..k, menu.configs.is_multicolor)
                            ImGui.SetNextItemWidth(ctx, 150)
                            GUI.is_save_us.check, menu.configs.thick = ImGui.SliderInt(ctx, '##Thickness##' .. k,
                                menu.configs.thick, 1, 10)
                            if k ~= #dmenu then
                                ImGui.Separator(ctx)
                            end
                        end
                        ImGui.EndMenu(ctx)
                    end
                end
                ImGui.EndMenu(ctx)
            end

            if UserSettings.Tips then ToolTip("Save/Load Presets Globally. Store Groups and Settings") end

            if ImGui.BeginMenu(ctx, 'Actions##Menu') then
                if ImGui.MenuItem(ctx, 'Untag Selected Items') then
                    UntagSelectedItems(proj)
                end
                ImGui.EndMenu(ctx)
            end


            -- Dock
            local reval_dock = ImGui.IsWindowDocked(ctx)
            local dock_text = reval_dock and 'Undock' or 'Dock'

            if ImGui.MenuItem(ctx, dock_text) then
                if reval_dock then -- Already Docked
                    SetDock = 0
                else           -- Not docked
                    SetDock = -3 -- Dock to the right
                end
            end
            ImGui.EndMenuBar(ctx)
        end
        --------- Get MIDI button
        ChangeColor(0.4,0.55,0.4,1)
        local label = Alt and 'Get Sequencer Track' or 'Get Sequencer Item'
        ImGui.Button(ctx, label, -2)
        if ImGui.IsItemClicked(ctx) then
            ProjTable[proj].Sequencers = is.OpenaAllSelectedMediaAsSequencer(0, not Alt, version)
        end
        
        if UserSettings.Tips then ToolTip("Select the MIDI items with the notes where the items will be placed. Hold Alt to select a tracks instead of items.") end
        ImGui.PopStyleColor(ctx, 3)

        -- Check sequencers
        if ProjTable[proj].Sequencers then
            is.CheckSequencers(ProjTable[proj].Sequencers)
        end
            -- Tab Bar
        if ProjTable[proj].Sequencers and #ProjTable[proj].Sequencers > 0 then
            local sequencers = ProjTable[proj].Sequencers -- hotline
            local sequencer = sequencers[sequencers.focus]
            local groups = sequencer.groups

            -- Sequencer dropdown
            local sequencer_name = is.GetSequencerName(sequencer)
            ImGui.SetNextItemWidth(ctx, -1)
            if ImGui.BeginCombo(ctx, '##SequencersCombo', sequencer_name) then
                for k, v in ipairs(sequencers) do
                    local loop_sname = is.GetSequencerName(v)
                    if ImGui.Selectable(ctx, loop_sname..'##sequencers'..k, k == sequencers.focus) then
                        sequencers.focus = k
                    end
                    -- Copy Paste Area.
                    CopyPasteSequencerSettings(v)
                end
                ImGui.EndCombo(ctx)
            end 
            CopyPasteSequencerSettings(sequencers[sequencers.focus])

            ImGui.Separator(ctx)
            
            if ImGui.BeginTabBar(ctx, 'Groups', ImGui.TabBarFlags_AutoSelectNewTabs ) then
                local remove_t = {}
                for i,v in ipairs(groups) do -- Loop Tabs
                    ChangeColorTab((0.05*i),0.55,0.4,1) -- Change Tab Colors
                    local open, keep = ImGui.BeginTabItem(ctx, ('%s###tab%s'):format(groups[i].name, groups[i].Settings.GUID), true) -- Start each tab

                    -- Popup to rename
                    local is_popup_now = false
                    if ImGui.BeginPopupContextItem(ctx) then 
                        if ImGui.IsWindowAppearing(ctx) then
                            PreventPassKeys2 = CheckPreventPassThrough(true, 'rename'..i, PreventPassKeys2) 
                        end
                        is_popup_now = true

                        ImGui.Text(ctx, 'Edit name:')
                        _, groups[i].name = ImGui.InputText(ctx, "###nameinput", groups[i].name)
                        
                        -- Enter
                        if ImGui.IsKeyDown(ctx, ImGui.Key_Enter) then
                            PreventPassKeys2 = CheckPreventPassThrough(false, 'rename'..i, PreventPassKeys2)
                            ImGui.CloseCurrentPopup(ctx)
                        end

                        ImGui.Separator(ctx)
                        if ImGui.Button(ctx, 'Duplicate Group', -1) then
                            local new_group = BlankGroup.Duplicate(groups[i])
                            table.insert(groups, i+1, new_group)
                        end
                        ImGui.Separator(ctx)

                        if ImGui.Button(ctx, 'Copy Settings', -1) then
                            CopyGroupSettings = table_copy(groups[i])
                        end

                        if CopyGroupSettings and ImGui.Button(ctx, 'Paste Settings', -1) then
                            local old_name = groups[i].name 
                            local old_guid = groups[i].Settings.GUID
                            groups[i] = table_copy(CopyGroupSettings)
                            groups[i].name = old_name
                            groups[i].Settings.GUID = old_guid
                            GUI.is_save.check = true
                        end

                        GUI.groups_popup.was_open = true
                        ImGui.EndPopup(ctx)
                    end

                    if GUI.groups_popup.was_open and not is_popup_now then
                        GUI.is_save.check = true
                        PreventPassKeys2 = CheckPreventPassThrough(false, 'rename'..i, PreventPassKeys2)
                        GUI.groups_popup.was_open = false
                        IsPopUpOpen = nil
                    end

                    if open then -- Inside Each Tab
                        if ImGui.BeginChild(ctx, '##Child'..i, -1, 400) then
                            
                            --Do Things at this tab

                            --Item Group
                                    --------- Get Items sequence Buttons
                            ChangeColorButton((0.05*i),0.6,0.4,1)
                            local label = Alt and 'Get Track Sources' or 'Get Item Sources'
                            if ImGui.Button(ctx, label, -1) then
                                if not Shift and not Ctrl and not Alt then -- Get Items
                                    groups[i].list_sequence = ListItems()
                                elseif Alt and not Shift and not Ctrl then -- Get Tracks
                                    groups[i].list_sequence = ListTracks(0)                        
                                elseif Shift then -- Select Sources
                                    if groups[i].list_sequence and #groups[i].list_sequence > 1 then
                                        reaper.Undo_BeginBlock()
                                        reaper.PreventUIRefresh(1)
                                        LoadSelectedItems(groups[i].list_sequence)
                                        reaper.UpdateArrange()
                                        reaper.PreventUIRefresh(-1)
                                        reaper.Undo_EndBlock2(0, 'Item Sampler: Select Item Sequence', -1)
                                    else
                                        print('No Item Sequence')
                                    end
                                end

                                if not Shift then
                                    GUI.is_save.check = true
                                end
                            end
                            if UserSettings.Tips then ToolTip("Get the selected items as the sequence of items to be placed on the notes of the MIDI Item\nShift: Select the sequence of items in the project. Hold Alt to select a track as source(s).") end

                            ImGui.PopStyleColor(ctx, 3)
                            --local GUIIsMaxClicked

                            --Sources
                            local opn = ImGui.TreeNode(ctx, 'Sources', ImGui.TreeNodeFlags_DrawLinesFull)
                            CopyPasteContext('list_sequence',  groups[i])
                            if opn then
                                if ImGui.BeginListBox(ctx,  '###sourceslist',-1,150) then
                                    if not groups[i].list_sequence or #groups[i].list_sequence == 0 then 
                                        ImGui.Text(ctx, '--- No Sources Selected! ---')
                                    else
                                        local remove_list = {}
                                        for idx, v in pairs(groups[i].list_sequence) do
                                            local is_item = reaper.ValidatePtr(v, 'MediaItem*')
                                            local is_track = reaper.ValidatePtr(v, 'MediaTrack*')
                                            -- Shource deleted
                                            if not is_item and not is_track then
                                                remove_list[#remove_list+1] = idx
                                                goto continue
                                            end
                                            -- Draw Source Selectable
                                            local name
                                            if is_item then
                                                local take = reaper.GetActiveTake(v)
                                                local _, i_name = reaper.GetSetMediaItemTakeInfo_String(take, 'P_NAME', '', false)
                                                name = 'Item: '..i_name
                                            else -- Assumes is a track
                                                local _, t_name = reaper.GetSetMediaTrackInfo_String(v, 'P_NAME', '', false)
                                                if t_name == '' then
                                                    local t_name_str = reaper.GetMediaTrackInfo_Value(v, 'IP_TRACKNUMBER')
                                                    t_name = '#'..string.format('%d', t_name_str)
                                                end
                                                name = 'Track: '..t_name
                                            end
                                            if ImGui.Selectable(ctx,  name..'##Source'..idx, false) then
                                                reaper.Undo_BeginBlock()
                                                if is_item then
                                                    if not Ctrl then
                                                        reaper.SelectAllMediaItems(0, false)
                                                    end
                                                    reaper.SetMediaItemSelected(v, true)
                                                else
                                                    if not Ctrl then
                                                        reaper.SetOnlyTrackSelected(v)
                                                    else
                                                        reaper.SetTrackSelected(v, true)
                                                    end
                                                end
                                                reaper.Undo_EndBlock2(0, 'Item Sampler: Select Source', -1)
                                                reaper.UpdateArrange()
                                            end
                                            -- Right Click
                                            if ImGui.BeginPopupContextItem(ctx, name..'##ContextSource'..idx) then
                                                if ImGui.Selectable(ctx,  'Remove'..'##Source'..idx, false) then
                                                    remove_list[#remove_list+1] = idx
                                                end
                                                ImGui.EndPopup(ctx)
                                            end
                                            ::continue::
                                        end
                                        -- Remove Sources
                                        if #remove_list > 0 then
                                            for r_idx = #remove_list, 1, -1 do
                                                local idx = remove_list[r_idx]
                                                table.remove(groups[i].list_sequence, idx)
                                            end
                                            GUI.is_save.check = true
                                        end
                                    end
                                    
                                    ImGui.EndListBox(ctx)
                                end
                                ImGui.TreePop(ctx)
                            end

                            --Range
                            local opn = ImGui.TreeNode(ctx, 'Range', ImGui.TreeNodeFlags_DrawLinesFull)
                            if ImGui.BeginPopupContextItem(ctx) then
                                if ImGui.Button(ctx, 'Copy Settings', 125) then
                                    GUI.copies.NoteRange = table_copy(groups[i].Settings.NoteRange)
                                    GUI.copies.VelocityRange = table_copy(groups[i].Settings.VelocityRange)
                                end

                                if GUI.copies.NoteRange and ImGui.Button(ctx, 'Paste Settings', 125) then
                                    groups[i].Settings.NoteRange = GUI.copies.NoteRange
                                    groups[i].Settings.VelocityRange = GUI.copies.VelocityRange
                                    GUI.is_save.check = true
                                end
                                ImGui.EndPopup(ctx)
                            end
                            if opn then
                                ImGui.PushItemWidth( ctx,  -15)
                                ImGui.Text(ctx, 'Note Range')
                                local min_note, max_note  = NumberToNote(groups[i].Settings.NoteRange.Min), NumberToNote(groups[i].Settings.NoteRange.Max) 
                                GUI.is_save.check, groups[i].Settings.NoteRange.Min, groups[i].Settings.NoteRange.Max = ImGui.DragIntRange2(ctx, '###a', groups[i].Settings.NoteRange.Min , groups[i].Settings.NoteRange.Max, 0.03, 0, 127,  'Min: '..min_note, "Max: "..max_note)

                                --- Pop Up Open
                                -- Check if double clicked and open pop up
                                if ImGui.IsItemHovered(ctx) and ImGui.IsMouseDoubleClicked( ctx, 0) then 
                                    ImGui.OpenPopup(ctx, 'rangepopup')
                                    PreventPassKeys2 = CheckPreventPassThrough(true, 'setnote', PreventPassKeys2)
                                    local mouse_x = ImGui.GetMousePos( ctx)
                                    GUIIsMaxClicked = mouse_x > (gui_x + (gui_w/2) + 10) 
                                end

                                -- Pop Up
                                local popup_setnote
                                if ImGui.BeginPopup(ctx, 'rangepopup') then
                                    popup_setnote = true
                                    if ImGui.IsWindowAppearing(ctx) then
                                        ImGui.SetKeyboardFocusHere(ctx)
                                    end
                                    if GUIIsMaxClicked == true then -------- Max Value
                                        ImGui.SetNextItemWidth( ctx,  60)      
                                        local max_text = NumberToNote(groups[i].Settings.NoteRange.Max)
                                        local bol, max_text = ImGui.InputText(ctx, '###New Notemax', max_text)
                                        if bol then
                                            max_text = MakeUpperCaseFirstLetter(max_text)
                                            if  IsStringNote(max_text) then 
                                                groups[i].Settings.NoteRange.Max  = NoteToNumber(max_text,4)
                                            end
                                            GUI.is_save.check = true
                                        end
                                    else ----------------------------------  Min Value
                                        ImGui.SetNextItemWidth( ctx,  60) 
                                        local min_text = NumberToNote(groups[i].Settings.NoteRange.Min)
                                        local bol, min_text = ImGui.InputText(ctx, '###New Notemin', min_text)
                                        if bol then
                                            min_text = MakeUpperCaseFirstLetter(min_text)
                                            if  IsStringNote(min_text) then 
                                                groups[i].Settings.NoteRange.Min  = NoteToNumber(min_text,4)
                                            end
                                            GUI.is_save.check = true
                                        end
                                    end
                                    if  ImGui.IsKeyPressed(ctx, ImGui.Key_Enter) then
                                        ImGui.CloseCurrentPopup(ctx)
                                        PreventPassKeys2 = CheckPreventPassThrough(false, 'setnote', PreventPassKeys2)
                                    end

                                    --boolean retval, string buf = ImGui.InputText(ImGui_Context ctx, string label, string buf, number flags = nil)
                                    ImGui.EndPopup(ctx)
                                end

                                if GetSourceKey('setnote', PreventPassKeys2) and not popup_setnote then
                                    PreventPassKeys2 = CheckPreventPassThrough(false, 'setnote', PreventPassKeys2)
                                end

                                if UserSettings.Tips then ToolTip("Set a Note Range for the Group. Only paste if MIDI note in between these notes(included)") end

                                -----------------
                                ImGui.Text(ctx, 'Velocity Range')
                                GUI.is_save.check, groups[i].Settings.VelocityRange.Min, groups[i].Settings.VelocityRange.Max = ImGui.DragIntRange2(ctx, '###b', groups[i].Settings.VelocityRange.Min, groups[i].Settings.VelocityRange.Max, 0.03, 0, 127,  'Min: %d', "Max: %d")
                                ImGui.PopItemWidth(ctx)
                                if UserSettings.Tips then ToolTip("Set a Velocity Range for the Group. Only paste if MIDI note velocity is in between these values(included)") end

                                ImGui.TreePop(ctx)
                            end
                            
                            --Trim


                            
                            local opn = ImGui.TreeNode(ctx, 'Trim', ImGui.TreeNodeFlags_DrawLinesFull)
                            if ImGui.BeginPopupContextItem(ctx) then
                                local keys = {'Erase', 'Is_trim_ItemEnd', 'Is_trim_StartNextNote', 'Is_trim_EndNote'}
                                if ImGui.Button(ctx, 'Copy Settings', 125) then
                                    GUI.copies.Trim = {}
                                    for k, key in ipairs(keys) do
                                        GUI.copies.Trim[key] = groups[i].Settings[key] 
                                    end
                                end

                                if GUI.copies.Trim and ImGui.Button(ctx, 'Paste Settings', 125) then
                                    for key, val in pairs(GUI.copies.Trim) do
                                        groups[i].Settings[key] = val
                                    end
                                    GUI.is_save.check = true
                                end
                                ImGui.EndPopup(ctx)
                            end
                            if opn then
                                if ImGui.Checkbox(ctx, 'Clean Area Before Paste',groups[i].Settings.Erase) then
                                    groups[i].Settings.Erase = not groups[i].Settings.Erase
                                    GUI.is_save.check = true
                                end
                                if UserSettings.Tips then ToolTip("Before pasting delete Any Item in the space of the Pasted Items") end
                
                                if ImGui.Checkbox(ctx, 'Trim Items Using MIDI Item End',groups[i].Settings.Is_trim_ItemEnd) then
                                    groups[i].Settings.Is_trim_ItemEnd = not groups[i].Settings.Is_trim_ItemEnd
                                    GUI.is_save.check = true
                                end
                                if UserSettings.Tips then ToolTip("The pasted items will be trimmed at the end of the MIDI item") end
                
                                if ImGui.Checkbox(ctx, 'Trim Items Using Start Next MIDI Note',groups[i].Settings.Is_trim_StartNextNote) then
                                    groups[i].Settings.Is_trim_StartNextNote = not groups[i].Settings.Is_trim_StartNextNote
                                    GUI.is_save.check = true
                                end
                                if UserSettings.Tips then ToolTip("The pasted items will be trimmed at the start of the next MIDI note") end
                
                                if ImGui.Checkbox(ctx, 'Trim Items Using End MIDI Note',groups[i].Settings.Is_trim_EndNote) then
                                    groups[i].Settings.Is_trim_EndNote = not groups[i].Settings.Is_trim_EndNote
                                    GUI.is_save.check = true
                                end
                                if UserSettings.Tips then ToolTip("The pasted items will be trimmed at the end of the MIDI note") end

                                ImGui.TreePop(ctx)
                            end

                            --Velocity
                            local opn = ImGui.TreeNode(ctx, 'Velocity', ImGui.TreeNodeFlags_DrawLinesFull)
                            if ImGui.BeginPopupContextItem(ctx) then
                                local keys = {'Velocity', 'Vel_OriginalVal', 'Vel_Max', 'Vel_Min'}
                                if ImGui.Button(ctx, 'Copy Settings', 125) then
                                    GUI.copies.Velocity = {}
                                    for k, key in ipairs(keys) do
                                        GUI.copies.Velocity[key] = groups[i].Settings[key] 
                                    end
                                end

                                if GUI.copies.Velocity and ImGui.Button(ctx, 'Paste Settings', 125) then
                                    for key, val in pairs(GUI.copies.Velocity) do
                                        groups[i].Settings[key] = val
                                    end
                                    GUI.is_save.check = true
                                end
                                ImGui.EndPopup(ctx)
                            end
                            if opn then

                                if ImGui.Checkbox(ctx, 'Velocity Change Item dB',groups[i].Settings.Velocity) then
                                    groups[i].Settings.Velocity = not groups[i].Settings.Velocity
                                    GUI.is_save.check = true
                                end
                                
                                ImGui.PushItemWidth( ctx,  -120)

                                local name = 'Max dB added'
                                GUI.is_save.check, groups[i].Settings.Vel_Max = ImGui.InputInt(ctx,  name, groups[i].Settings.Vel_Max)
                                local focus = ImGui.IsItemFocused(ctx)
                                PreventPassKeys2 = CheckPreventPassThrough(focus, name,PreventPassKeys2)

                                local name = 'Max dB reduce'
                                GUI.is_save.check, groups[i].Settings.Vel_Min = ImGui.InputInt(ctx,  name, groups[i].Settings.Vel_Min)
                                local focus = ImGui.IsItemFocused(ctx)
                                PreventPassKeys2 = CheckPreventPassThrough(focus, name,PreventPassKeys2)

                                ImGui.PopItemWidth(ctx)

                                ImGui.PushItemWidth( ctx,  -120)
                                GUI.is_save.check, groups[i].Settings.Vel_OriginalVal = ImGui.SliderInt(ctx, 'Velocity to use\noriginal Item dB', groups[i].Settings.Vel_OriginalVal, 0, 127)
                                ImGui.PopItemWidth(ctx)

                            ImGui.TreePop(ctx)
                            end

                            --Pitch
                            local opn = ImGui.TreeNode(ctx, 'Pitch', ImGui.TreeNodeFlags_DrawLinesFull)
                            if ImGui.BeginPopupContextItem(ctx) then
                                local keys = {'Pitch', 'Pitch_Original'}
                                if ImGui.Button(ctx, 'Copy Settings', 125) then
                                    GUI.copies.Pitch = {}
                                    for k, key in ipairs(keys) do
                                        GUI.copies.Pitch[key] = groups[i].Settings[key] 
                                    end
                                end

                                if GUI.copies.Pitch and ImGui.Button(ctx, 'Paste Settings', 125) then
                                    for key, val in pairs(GUI.copies.Pitch) do
                                        groups[i].Settings[key] = val
                                    end
                                    GUI.is_save.check = true
                                end
                                ImGui.EndPopup(ctx)
                            end
                            if opn then

                                if ImGui.Checkbox(ctx, 'MIDI Pitch Note Change Item Pitch',groups[i].Settings.Pitch) then
                                    groups[i].Settings.Pitch = not groups[i].Settings.Pitch
                                    GUI.is_save.check = true
                                end
                                
                                ImGui.PushItemWidth( ctx,  -100)
                                GUI.is_save.check, groups[i].Settings.Pitch_Original = ImGui.SliderInt(ctx, 'Original Pitch\nat MIDI Note', groups[i].Settings.Pitch_Original, 0, 127, NumberToNote(groups[i].Settings.Pitch_Original, true))
                                ImGui.PopItemWidth(ctx)

                                ImGui.TreePop(ctx)
                            end

                            --Stretch
                            local opn = ImGui.TreeNode(ctx, 'Stretch', ImGui.TreeNodeFlags_DrawLinesFull)
                            CopyPasteContext('stretch', groups[i].Settings)
                            if opn then
                                ImGui.PushItemWidth( ctx,  -140)
                                GUI.is_save.check, groups[i].Settings.stretch.is_stretch = ImGui.Checkbox(ctx, 'MIDI Velocity affects Item stretch', groups[i].Settings.stretch.is_stretch)
                                
                                local change
                                change, groups[i].Settings.stretch.min_stretch, groups[i].Settings.stretch.max_stretch  =  ImGui.DragDouble2(ctx, 'Stretch', groups[i].Settings.stretch.min_stretch, groups[i].Settings.stretch.max_stretch, 0.0005, GUI.stretch.min, math.huge)
                                if change then
                                    if groups[i].Settings.stretch.min_stretch > groups[i].Settings.stretch.max_stretch then
                                        groups[i].Settings.stretch.min_stretch = groups[i].Settings.stretch.max_stretch
                                    end
                                    GUI.is_save.check = true
                                end

                                GUI.is_save.check, groups[i].Settings.stretch.original_stretch = ImGui.SliderInt(ctx, 'Velocity to use\noriginal Item Stretch', groups[i].Settings.stretch.original_stretch, 0, 127)
                                ImGui.PopItemWidth(ctx)
                                ImGui.TreePop(ctx)
                            end

                            --Track Target
                            local opn = ImGui.TreeNode(ctx, 'Target Tracks', ImGui.TreeNodeFlags_DrawLinesFull)
                            CopyPasteContext('Target Tracks',  groups[i].Settings)
                            if opn then
                                if ImGui.Button(ctx, 'Get Selected Tracks') then
                                    groups[i].Settings.Targets = ListTracks(0)
                                    GUI.is_save.check = true
                                end
                                if UserSettings.Tips then ToolTip("Select the tracks where the created items will be placed. If multiple tracks are selected, it will randomly choose one per item.") end

                                if ImGui.BeginListBox(ctx,  '###targetlist',-1,150) then
                                    if groups[i].Settings.Targets and #groups[i].Settings.Targets > 0 then
                                        local remove = {}
                                        for k, v in ipairs(groups[i].Settings.Targets) do 
                                            -- Check if source is deleted
                                            local is_track = reaper.ValidatePtr(v, 'MediaTrack*')
                                            if not is_track then
                                                remove[#remove+1] = k
                                                goto continue
                                            end
                                            -- Name
                                            local _, t_name = reaper.GetSetMediaTrackInfo_String(v, 'P_NAME', '', false)
                                            if t_name == '' then
                                                local _
                                                local t_val = reaper.GetMediaTrackInfo_Value(v, 'IP_TRACKNUMBER')
                                                t_name = string.format('%d', t_val)
                                            end
                                            t_name = 'Track: '..t_name
                                            -- Selectable
                                            if ImGui.Selectable(ctx, t_name..'##TargetTrack'..k) then
                                                if not Ctrl then
                                                    reaper.SetOnlyTrackSelected(v)
                                                else
                                                    reaper.SetTrackSelected(v, true)
                                                end
                                            end
                                            -- Right Click
                                            if ImGui.BeginPopupContextItem(ctx, t_name..'##ContextSource'..k) then
                                                if ImGui.Selectable(ctx,  'Remove'..'##Source'..k, false) then
                                                    remove[#remove+1] = k
                                                end
                                                ImGui.EndPopup(ctx)
                                            end
                                            ::continue::
                                        end
                                        if #remove > 0 then
                                            for idx = #remove, 1, -1 do
                                                table.remove(groups[i].Settings.Targets, remove[idx])
                                            end
                                            GUI.is_save.check = true
                                        end
                                    end
                                    ImGui.EndListBox(ctx)
                                end
                                ImGui.TreePop(ctx)
                            end

                            ImGui.EndChild(ctx)
                        end
                        ImGui.EndTabItem(ctx)
                    end
                    
                    
                    if not keep then -- If Close
                        remove_t[#remove_t+1] = i
                    end
                end

                if #remove_t > 0 then
                    for k, v in ipairs(remove_t) do
                        table.remove(groups, v)
                    end
                    GUI.is_save.check = true
                end

                if ImGui.TabItemButton(ctx, '+', ImGui.TabItemFlags_Trailing | ImGui.TabItemFlags_NoTooltip) then
                    groups[#groups+1] = BlankGroup:Create('G'..#groups+1)
                    GUI.is_save.check = true
                end

                if ImGui.IsItemClicked(ctx, ImGui.MouseButton_Right) then
                    GUI.create_popup.push_open = true
                end

                ImGui.EndTabBar(ctx)
                
                ResetStyleCount()
            end

            if GUI.create_popup.push_open then
                ImGui.OpenPopup(ctx, GUI.create_popup.name)
                GUI.create_popup.push_open = false
            end

            ImGui.SetNextWindowSizeConstraints(ctx, 150, 100, math.huge, math.huge)
            if ImGui.BeginPopup(ctx, GUI.create_popup.name) then
                if ImGui.IsWindowAppearing(ctx) and not groups[GUI.create_popup.groups.settings] then
                    GUI.create_popup.groups.settings = 0
                end
                ImGui.Text(ctx, 'Using the selected')
                ImGui.SameLine(ctx)
                ImGui.Text(ctx, '[')
                ImGui.SameLine(ctx)
                _, GUI.create_popup.source.is_item = ImGui.RadioButtonEx(ctx, 'items', GUI.create_popup.source.is_item, 0)
                ImGui.SameLine(ctx)
                _, GUI.create_popup.source.is_item = ImGui.RadioButtonEx(ctx, 'tracks', GUI.create_popup.source.is_item, 1)
                ImGui.SameLine(ctx)
                ImGui.Text(ctx, ']')

                ImGui.Text(ctx, 'as sources, create ')
                ImGui.SameLine(ctx)
                ImGui.Text(ctx, '[')
                ImGui.SameLine(ctx)
                _, GUI.create_popup.groups.is_one = ImGui.RadioButtonEx(ctx, 'one', GUI.create_popup.groups.is_one, 0)
                ImGui.SameLine(ctx)
                _, GUI.create_popup.groups.is_one = ImGui.RadioButtonEx(ctx, 'multiple', GUI.create_popup.groups.is_one, 1)
                ImGui.SameLine(ctx)
                ImGui.Text(ctx, ']')
                ImGui.SameLine(ctx)
                ImGui.Text(ctx, GUI.create_popup.groups.is_one == 0 and 'group.' or 'groups.')

                ImGui.Text(ctx, 'Using the settings of the group')
                ImGui.SameLine(ctx)
                
                local default_txt = 'Default Settings'
                local wa,ha =ImGui.GetContentRegionAvail(ctx)
                ImGui.SetNextItemWidth(ctx, wa)
                local combo_name = GUI.create_popup.groups.settings == 0 and default_txt or groups[GUI.create_popup.groups.settings].name
                if ImGui.BeginCombo(ctx, '##combotoselectsetting', combo_name) then
                    if ImGui.Selectable(ctx, default_txt) then
                        GUI.create_popup.groups.settings = 0
                    end
                    for gi, group in ipairs(groups) do
                        local name = group.name
                        if ImGui.Selectable(ctx, name..'##'..group.Settings.GUID) then
                            GUI.create_popup.groups.settings = gi
                        end
                    end
                    ImGui.EndCombo(ctx)
                end

                _, GUI.create_popup.groups.is_replacing = ImGui.Checkbox(ctx, 'Replacing existing groups', GUI.create_popup.groups.is_replacing)

                if GUI.create_popup.groups.is_one == 1 then
                    ImGui.Separator(ctx)
                    _, GUI.create_popup.groups.range.set_by_key = ImGui.Checkbox(ctx, 'Assign each group to a different pitch', GUI.create_popup.groups.range.set_by_key)
                    ImGui.BeginDisabled(ctx, not GUI.create_popup.groups.range.set_by_key)
                    local label = 'Starting Pitch'
                    local wa,ha =ImGui.GetContentRegionAvail(ctx)
                    local tw = ImGui.CalcTextSize(ctx, label)
                    ImGui.SetNextItemWidth(ctx, wa - tw - 5)
                    _, GUI.create_popup.groups.range.start_pitch = ImGui.SliderInt(ctx, 'Starting Pitch', GUI.create_popup.groups.range.start_pitch, 0, 127, NumberToNote(GUI.create_popup.groups.range.start_pitch, true))
                    ImGui.EndDisabled(ctx)
                end

                ImGui.Separator(ctx)
                ChangeColor(0.38,0.48,0.4,1)
                local txt = GUI.create_popup.groups.is_one == 0 and 'Group' or 'Groups'
                if ImGui.Button(ctx, 'Create '..txt,  450) then
                    local group_model = (GUI.create_popup.groups.settings == 0 and BlankGroup:Create('G'..#groups+1)) or groups[GUI.create_popup.groups.settings]
                    local sources = {}
                    local f_enum = ((GUI.create_popup.source.is_item == 0) and DL.enum.SelectedMediaItem) or DL.enum.SelectedTracks
                    for source in f_enum(proj) do
                        sources[#sources+1] = source
                    end
                    local new_groups
                    if #sources > 0 then
                        new_groups = BlankGroup.Create2(proj, GUI.create_popup.groups, group_model, sources)
                    else
                        print('Please select at least one ' .. ((GUI.create_popup.source.is_item == 0 and 'item') or 'track'))
                    end
                    if #new_groups > 0 then
                        if GUI.create_popup.groups.is_replacing then
                            sequencer.groups = new_groups
                        else
                            for gi, group in ipairs(new_groups) do
                                table.insert(sequencer.groups, group)
                            end
                        end
                        GUI.is_save.check = true
                    end
                end
                ImGui.PopStyleColor(ctx, 3)

                ImGui.EndPopup(ctx)
            end
            
            ImGui.Separator(ctx)
            ImGui.Separator(ctx)


            --------Place Button
            ChangeColor(1,0.6,0.4,1)
            ImGui.Button(ctx, 'Place in Sequence', -2)
            if ImGui.IsItemClicked( ctx) then
                local is_reverse = Ctrl -- is ctrl down? 
                PlaceSequenceInGroups(proj, sequencers, false, is_reverse, false)
            end
            if UserSettings.Tips then ToolTip("Click: Paste the items sequence in order Ctrl+Click: Paste the sequence in reverse order") end
            ImGui.PopStyleColor(ctx, 3); 


            --------Place Random
            ChangeColor(0.15,0.6,0.4,1)
            ImGui.Button(ctx, 'Place Random', -2)
            if ImGui.IsItemClicked( ctx) then
                local is_rand_sequence = Ctrl -- is ctrl down?
                PlaceSequenceInGroups(proj, sequencers, true, false, is_rand_sequence) 
            end
            if UserSettings.Tips then ToolTip("Click: Paste the items sequence randomly Ctrl+Click: Paste the sequence randomly without repetitions") end
            ImGui.PopStyleColor(ctx, 3);
            -------- List Box

            if ImGui.TreeNode(ctx, 'Group Editor', ImGui.TreeNodeFlags_NoTreePushOnOpen) then 
                local text = 'X' -- Text for in range cells
                local t_w, t_h = ImGui.CalcTextSize(ctx, text)
                --local cell_height = 
                if ImGui.BeginTable(ctx, '##Pichgrideditor', 1 + #groups, ImGui.TableFlags_Borders | ImGui.TableFlags_BordersH | ImGui.TableFlags_ScrollY, -1, -1) then
                    ImGui.TableSetupColumn(ctx, 'Note', ImGui.TableColumnFlags_WidthFixed | ImGui.TableColumnFlags_NoSort, 75)
                    for gi, group in ipairs(groups) do
                        ImGui.TableSetupColumn(ctx, group.name..'##'..group.Settings.GUID, ImGui.TableColumnFlags_NoSort)
                    end
                    ImGui.TableSetupScrollFreeze(ctx, 0, 1)

                    -- Add Header
                    ImGui.TableNextRow(ctx)
                    ImGui.TableSetColumnIndex(ctx, 0)
                    ImGui.TableHeader(ctx, 'Note')

                    for gi, group in ipairs(groups) do
                        ImGui.TableSetColumnIndex(ctx, gi)
                        local is_gray_out = not group.Selected
                        if is_gray_out then
                            ImGui.PushStyleColor(ctx, ImGui.Col_TableHeaderBg, 0x562B26FF)
                            ImGui.PushStyleColor(ctx, ImGui.Col_HeaderHovered, 0x7E3931FF)
                            ImGui.PushStyleColor(ctx, ImGui.Col_HeaderActive, 0xAD675EFF)
                        end

                        ImGui.TableHeader(ctx, group.name..'##'..group.Settings.GUID)
                        if ImGui.IsItemHovered(ctx) and ImGui.IsMouseReleased(ctx, ImGui.MouseButton_Left) then
                            group.Selected = not group.Selected
                        end

                        if is_gray_out then
                            ImGui.PopStyleColor(ctx, 3)
                        end
                    end

                    -- Normal rows

                    for note_idx = 127, 0, -1 do
                        if GUI.grid_editor.first_run and note_idx == 58 then
                            ImGui.SetScrollHereY(ctx, 1)
                            GUI.grid_editor.first_run = false
                        end
                        ImGui.TableNextRow(ctx)
                        ImGui.TableSetColumnIndex(ctx, 0)
                        local color = GUI.grid_editor.accidents[note_idx % 12] and 0x404040FF or 0x727272FF
                        ImGui.TableSetBgColor(ctx, ImGui.TableBgTarget_RowBg0, color)
                        ImGui.Text(ctx, NumberToNote(note_idx))
                        for gi, group in ipairs(groups) do
                            ImGui.TableNextColumn(ctx)
                            -- Text
                            local in_range = false
                            if (note_idx <= group.Settings.NoteRange.Max) and (note_idx >= group.Settings.NoteRange.Min) then
                                in_range = true
                            end
                            local wa, ha = ImGui.GetContentRegionAvail(ctx)
                            local x, y = ImGui.GetCursorPos(ctx)
                            local xs, ys = ImGui.GetCursorScreenPos(ctx)
                            -- Selectable Button
                            local label = '##col'..gi..'row'..note_idx
                            if ImGui.Selectable(ctx, label) then
                                if Ctrl then
                                    group.Settings.Pitch_Original = note_idx
                                elseif not Shift then
                                    group.Settings.Pitch_Original = note_idx
                                    group.Settings.NoteRange.Min = note_idx 
                                    group.Settings.NoteRange.Max = note_idx 
                                else -- normal click 
                                    -- Check which is closest 
                                    local min = math.abs(note_idx - group.Settings.NoteRange.Min)
                                    local max = math.abs(note_idx - group.Settings.NoteRange.Max)
                                    if group.Settings.NoteRange.Min == group.Settings.NoteRange.Max then
                                        if note_idx > group.Settings.NoteRange.Max then
                                            group.Settings.NoteRange.Max = note_idx
                                        else
                                            group.Settings.NoteRange.Min = note_idx
                                        end
                                    elseif min > max then
                                        group.Settings.NoteRange.Max = note_idx
                                    else
                                        group.Settings.NoteRange.Min = note_idx
                                    end
                                end

                                GUI.is_save.check = true
                            end
                            -- Drawing
                            if note_idx == group.Settings.Pitch_Original then
                                local dl = ImGui.GetWindowDrawList(ctx)
                                ImGui.DrawList_AddRect(dl, xs-5, ys-2, xs+wa+5, ys+t_h+3, 0xFFDFF7FF, nil, nil, 1)
                            end
                            -- Text
                            if in_range then
                                ImGui.SetCursorPos(ctx, x + (wa - t_w)/2, y)
                                ImGui.Text(ctx, text)
                            end
                        end
                    end
                    ImGui.EndTable(ctx)
                end
            end


            if GUI.is_save[1] then
                is.SaveSequencer(sequencer.seq, sequencer, sequencer.is_item)
                if UserSettings.sequencers.rename_note_names then
                    is.RenameMIDINotes(proj, sequencer)
                end
                GUI.is_save[1] = nil
                GUI.is_save.check = nil
            end
        end

        if GUI.is_save_us[1] then
            config.Save(ExtStates.ext_name, ExtStates.user_settings.key, UserSettings)
            GUI.is_save_us[1] = nil
            GUI.is_save_us.check = nil
        end


        ----
        ImGui.End(ctx)
    end        

    ImGui.PopFont(ctx)
    PopStyle()
    --- Invisible Window

    local dw = GUI.sequencers.draw_window
    local dw_options = UserSettings.gui.draw
    if (ProjTable[proj].Sequencers) and (#ProjTable[proj].Sequencers > 0) and (dw_options.active.is_draw) then
        ------ Get info about arrange window position
        -- Get Window information 
        dw.arrange = {}
        _, dw.arrange.left, dw.arrange.top, dw.arrange.right, dw.arrange.bottom = reaper.JS_Window_GetRect( dw.arrange_win )
        dw.arrange.width = dw.arrange.right - dw.arrange.left
        -- Get Scroll information
        if not dw.scroll_size then
            local retval, position, pageSize, min, max, trackPos = reaper.JS_Window_GetScrollInfo(dw.arrange_win, "HORZ")
            dw.scroll_size = dw.arrange.width  - pageSize
        end
        dw.arrange.right = dw.arrange.right - dw.scroll_size
        dw.arrange.bottom = dw.arrange.bottom - dw.scroll_size

        -- Set window position / only when needed
        local current_pos = dw.arrange.left .. ';' .. dw.arrange.top .. ';' .. dw.arrange.right .. ';' .. dw.arrange.bottom 
        if dw.LastWinPosition ~= current_pos then
            dw.LastWinPosition = current_pos 
            -- convert native screen rect -> ImGui logical coords for window pos/size CHANGE
            local i_left, i_top = ImGui.PointConvertNative(ctx, dw.arrange.left, dw.arrange.top)
            local i_right, i_bot = ImGui.PointConvertNative(ctx, dw.arrange.right, dw.arrange.bottom)   
            -- Set window pos / size
            ImGui.SetNextWindowPos(ctx, i_left, i_top)
            ImGui.SetNextWindowSize(ctx, i_right - i_left, i_bot - i_top)
        end

        -- Gatter information about Arrange time and Arrange Y 
        -- Time
        dw.arrange.start, dw.arrange.fim = reaper.GetSet_ArrangeView2(proj, false, 0, 0)
        dw.arrange.time_len  = dw.arrange.fim - dw.arrange.start
        dw.arrange.tpp = dw.arrange.time_len / dw.arrange.width-- time per pixel

        ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowBorderSize, 0)
        ImGui.PushStyleColor(ctx, ImGui.Col_ModalWindowDimBg, 0x00000000)-- No Modal dimming
        -- Create Window
        if ImGui.Begin(ctx, 'Item Sampler: Draw Window', true, dw.flags) then
            
            -- Collect items/tracks information to be drawn
            local is_multicolor = false
            do
                local sequencers = ProjTable[proj].Sequencers
                dw.sequencers = { 
                    track_info = {}, -- Store information about tracks, so it dont need to calculate twice
                    dl = ImGui.GetWindowDrawList(ctx)
                }
                for k, sequencer in ipairs(sequencers) do
                    -- The Sequencers
                    do 
                        local f = sequencer.is_item and GetItemImGuiCordinates or GetTrackItemAreaImGuiCordinates 
                        local bol, x1, y1, x2, y2 = f(sequencer.seq, dw.sequencers.track_info, dw)
                        local is_focused = k == sequencers.focus
                        local options = is_focused and dw_options.focused or dw_options.active
                        if bol then
                            dw.sequencers[#dw.sequencers + 1] = {
                                color = options.color,
                                thick = options.thick,
                                is_multicolor = options.is_multicolor,
                                cordinates = {
                                    x1 = x1,
                                    y1 = y1,
                                    x2 = x2,
                                    y2 = y2
                                }
                            }
                            is_multicolor = is_multicolor or  options.is_multicolor
                        end
                    end
                    if dw_options.target_tracks.is_draw or dw_options.sources.is_draw then
                        local groups = sequencer.groups
                        for k, group in ipairs(groups) do
                            -- Target Tracks
                            if dw_options.target_tracks.is_draw and group.Settings.Targets then
                                local options =  dw_options.target_tracks
                                for k, track in ipairs(group.Settings.Targets) do
                                    local bol, x1, y1, x2, y2 = GetTrackItemAreaImGuiCordinates(track, dw.sequencers.track_info, dw)
                                    if bol then
                                        dw.sequencers[#dw.sequencers + 1] = {
                                            color = options.color,
                                            thick = options.thick,
                                            is_multicolor = options.is_multicolor,
                                            cordinates = {
                                                x1 = x1,
                                                y1 = y1,
                                                x2 = x2,
                                                y2 = y2
                                            }
                                        }
                                        is_multicolor = is_multicolor or  options.is_multicolor
                                    end
                                end
                            end

                            --
                            if dw_options.sources.is_draw then
                                local options =  dw_options.sources
                                for k, source in ipairs(group.list_sequence) do
                                    local is_item = reaper.ValidatePtr(source, 'MediaItem*')
                                    local is_track = reaper.ValidatePtr(source, 'MediaTrack*')
                                    if (not is_item) and (not is_track) then 
                                        goto continue
                                    end
                                    local f = is_item and GetItemImGuiCordinates or GetTrackItemAreaImGuiCordinates 
                                    local bol, x1, y1, x2, y2 = f(source, dw.sequencers.track_info, dw)
                                    if bol then
                                        dw.sequencers[#dw.sequencers + 1] = {
                                            color = options.color,
                                            thick = options.thick,
                                            is_multicolor = options.is_multicolor,
                                            cordinates = {
                                                x1 = x1,
                                                y1 = y1,
                                                x2 = x2,
                                                y2 = y2
                                            }
                                        }
                                        is_multicolor = is_multicolor or options.is_multicolor
                                    end
                                    ::continue::
                                end
                            end
                        end
                    end
                end
            end

            -- Draw
            -- For multicolor only: create animated colors using HSV
            local col
            if is_multicolor then
                local velocity = 4
                local time = (reaper.time_precise() % velocity) / velocity
                local hue = {0,.1}
                col = {}
                for k, h in ipairs(hue) do
                    h = (time + h) % 1.0
                    local r,g,b = ImGui.ColorConvertHSVtoRGB(h, 1, 1)
                    col[#col+1] = ImGui.ColorConvertDouble4ToU32(r, g, b, 1)
                end
            end
        
            for k, sd in ipairs(dw.sequencers) do -- sd = sequencer draw
                local cord = sd.cordinates
                if sd.is_multicolor then
                    DL.imgui.DrawList_AddRectMultiColor(dw.sequencers.dl, cord.x1, cord.y1, cord.x2 , cord.y2, sd.thick, col[1], col[2], col[2], col[1])
                else
                    DL.imgui.DrawList_AddRect_Inside(dw.sequencers.dl, cord.x1, cord.y1, cord.x2 , cord.y2, sd.color, 0, nil, sd.thick)
                    --ImGui.DrawList_AddRect(dw.sequencers.dl, cord.x1, cord.y1, cord.x2 , cord.y2, sd.color, 0, nil, sd.thick)     -- the -1 comes because selected items increase 1pixel in all directions
                end
            end
        
            ImGui.End(ctx)
        end
        ImGui.PopStyleVar(ctx, 1)
        ImGui.PopStyleColor(ctx, 1)
    end

    if open then
        --demo.PopStyle(ctx)
        reaper.defer(loop)
    end
end


function GetTrackItemAreaImGuiCordinates(track, tracks_info, dw) 
    if tracks_info[track] and tracks_info[track].hide then
        return false
    end

    if not tracks_info[track] then
        tracks_info[track] = {
            y = reaper.GetMediaTrackInfo_Value(track, 'I_TCPY'),
            h = reaper.GetMediaTrackInfo_Value(track, 'I_TCPH')
        }

        if (tracks_info[track].y > dw.arrange.bottom) or ((tracks_info[track].y + tracks_info[track].h) < 0) then
            tracks_info[track].hide = true
            return false
        end
    end
    local x1 = dw.arrange.left 
    local y1 = dw.arrange.top + tracks_info[track].y
    local x2 = dw.arrange.right 
    local y2 = y1 + tracks_info[track].h
    y1 = math.max(dw.arrange.top, y1)
    y2 = math.min(dw.arrange.bottom, y2)

    local ix1, iy1 = ImGui.PointConvertNative(ctx, x1, y1)
    local ix2, iy2 = ImGui.PointConvertNative(ctx, x2, y2)
    return  true, ix1, iy1, ix2, iy2
end

function GetItemImGuiCordinates(item, tracks_info, dw)
    --if sequencer_draw.is_item then
    local track = reaper.GetMediaItemTrack(item)
    if tracks_info[track] and tracks_info[track].hide then
        return false
    end
    -- X
    local start = reaper.GetMediaItemInfo_Value(item, 'D_POSITION')
    local len = reaper.GetMediaItemInfo_Value(item, 'D_LENGTH')
    local fim = start + len
    if ((start < dw.arrange.start) and (fim < dw.arrange.start)) or (start > dw.arrange.fim) then             -- rule out items that are not in the width of the project
        return false
    end

    local x1 = dw.arrange.left + ((start - dw.arrange.start) / dw.arrange.tpp)
    local x2 = x1 + (len / dw.arrange.tpp)
    x1 = math.ceil(x1 + 0.5)
    x1 = math.max(x1, dw.arrange.left)
    x2 = math.ceil(x2 + 0.5)
    x2 = math.min(x2, dw.arrange.right)

    -- Y
    if not tracks_info[track] then
        tracks_info[track] = {
            y = reaper.GetMediaTrackInfo_Value(track, 'I_TCPY'),
            h = reaper.GetMediaTrackInfo_Value(track, 'I_TCPH')
        }

        if (tracks_info[track].y > dw.arrange.bottom) or ((tracks_info[track].y + tracks_info[track].h) < 0) then
            tracks_info[track].hide = true
            return false
        end
    end
    local item_y = reaper.GetMediaItemInfo_Value(item, 'I_LASTY')
    local y1 = dw.arrange.top + tracks_info[track].y + item_y
    local item_h = reaper.GetMediaItemInfo_Value(item, 'I_LASTH')
    local y2 = y1 + item_h
    y1 = math.max(y1, dw.arrange.top )
    y2 = math.min(y2, dw.arrange.bottom )


    -- Convert
    local ix1, iy1 = ImGui.PointConvertNative(ctx, x1, y1)
    local ix2, iy2 = ImGui.PointConvertNative(ctx, x2, y2)
    ix1 = ix1 - 1
    iy1 = iy1 - 1

    return true, ix1, iy1, ix2, iy2
end

function salvar(proj) -- OFF Right now
    local proj = proj or 0
    --UserPresets.LS_Hide = Settings

    UserPresets.Groups = Groups
    UserPresets.Settings = Settings
    local save = CovertUserDataToGUIDRecursive(UserPresets)
    local save = table.save(save)
    reaper.SetProjExtState( proj, 'ItemSampler', 'Groups', tostring(save) )
    --save_json(ProjectPath, 'Item Sampler configs', CovertUserDataToGUIDRecursive(Groups))
end

CheckRequirements()


GuiInit()
loop()
--reaper.atexit(salvar)
