--@noindex
Clouds = Clouds or {}
Clouds.Themes = {}

Clouds.Themes.White = {}
function Clouds.Themes.White.Push(ctx)
    
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_Alpha,                       1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_DisabledAlpha,               0.46)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowPadding,               8, 8)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowRounding,              7)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowBorderSize,            1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowMinSize,               32, 32)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowTitleAlign,            0, 0.5)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ChildRounding,               0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ChildBorderSize,             1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_PopupRounding,               8)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_PopupBorderSize,             1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_FramePadding,                4, 3)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_FrameRounding,               2)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_FrameBorderSize,             0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ItemSpacing,                 8, 4)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ItemInnerSpacing,            4, 4)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_IndentSpacing,               21)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_CellPadding,                 4, 2)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ScrollbarSize,               14)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ScrollbarRounding,           0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_GrabMinSize,                 12)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_GrabRounding,                0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabRounding,                 4)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabBorderSize,               0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabBarBorderSize,            1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TableAngledHeadersAngle,     0.610865)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TableAngledHeadersTextAlign, 0.5, 0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ButtonTextAlign,             0.5, 0.5)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SelectableTextAlign,         0, 0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextBorderSize,     3)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextAlign,          0, 0.5)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextPadding,        20, 3)

    ImGui.PushStyleColor(ctx, ImGui.Col_Text,                      0x000000FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TextDisabled,              0x808080FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_WindowBg,                  0xEEF7FFFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_ChildBg,                   0xEEF7FFFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PopupBg,                   0xFFEECEFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_Border,                    0x6E6E8080)
    ImGui.PushStyleColor(ctx, ImGui.Col_BorderShadow,              0x00000000)
    ImGui.PushStyleColor(ctx, ImGui.Col_FrameBg,                   0x7CC4FF8A)
    ImGui.PushStyleColor(ctx, ImGui.Col_FrameBgHovered,            0xB7DFFFE7)
    ImGui.PushStyleColor(ctx, ImGui.Col_FrameBgActive,             0xD7EBFCFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TitleBg,                   0xB7DFFFE7)
    ImGui.PushStyleColor(ctx, ImGui.Col_TitleBgActive,             0x6AB1F2B0)
    ImGui.PushStyleColor(ctx, ImGui.Col_TitleBgCollapsed,          0x6AB1F2B0)
    ImGui.PushStyleColor(ctx, ImGui.Col_MenuBarBg,                 0x4EAFF4EB)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarBg,               0x0064DD87)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrab,             0x0A1E3787)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrabHovered,      0x0A1E3787)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrabActive,       0x0A1E3787)
    ImGui.PushStyleColor(ctx, ImGui.Col_CheckMark,                 0x000000FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_SliderGrab,                0x5DACFFFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_SliderGrabActive,          0x4893E1FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_Button,                    0x7CC4FF8A)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonHovered,             0xB7DFFFE7)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonActive,              0xD7EBFCFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_Header,                    0x84C8FFFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_HeaderHovered,             0x84C8FFA8)
    ImGui.PushStyleColor(ctx, ImGui.Col_HeaderActive,              0x84C8FF84)
    ImGui.PushStyleColor(ctx, ImGui.Col_Separator,                 0x7D7D7D80)
    ImGui.PushStyleColor(ctx, ImGui.Col_SeparatorHovered,          0x1A66BFC7)
    ImGui.PushStyleColor(ctx, ImGui.Col_SeparatorActive,           0x1A66BFFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGrip,                0x4296FA33)
    ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGripHovered,         0x4296FAAB)
    ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGripActive,          0x4296FAF2)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabHovered,                0x4296FACC)
    ImGui.PushStyleColor(ctx, ImGui.Col_Tab,                       0x2E5994DC)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabSelected,               0x3369ADFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabSelectedOverline,       0x4296FAFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmed,                 0x111A26F8)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmedSelected,         0x23436CFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmedSelectedOverline, 0x808080FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_DockingPreview,            0x4296FAB3)
    ImGui.PushStyleColor(ctx, ImGui.Col_DockingEmptyBg,            0x333333FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotLines,                 0x9C9C9CFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotLinesHovered,          0xFF6E59FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotHistogram,             0xE6B300FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotHistogramHovered,      0xFF9900FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableHeaderBg,             0xFFC27487)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableBorderStrong,         0x000000FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableBorderLight,          0x3B3B40FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableRowBg,                0x00000000)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableRowBgAlt,             0xA5D7FF74)
    ImGui.PushStyleColor(ctx, ImGui.Col_TextSelectedBg,            0x4296FA59)
    ImGui.PushStyleColor(ctx, ImGui.Col_DragDropTarget,            0xFFFF00E6)
    ImGui.PushStyleColor(ctx, ImGui.Col_NavHighlight,              0x4296FAFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_NavWindowingHighlight,     0xFFFFFFB3)
    ImGui.PushStyleColor(ctx, ImGui.Col_NavWindowingDimBg,         0xCCCCCC33)
    ImGui.PushStyleColor(ctx, ImGui.Col_ModalWindowDimBg,          0xCCCCCC59)
end

function Clouds.Themes.White.Pop(ctx)
    ImGui.PopStyleColor(ctx, 57)
    ImGui.PopStyleVar(ctx, 32)    
end


--- Dark
Clouds.Themes.Dark = {}
function Clouds.Themes.Dark.Push(ctx)
    ImGui.PushStyleColor(ctx, ImGui.Col_Text,                      0xFFFFFFF2)
    ImGui.PushStyleColor(ctx, ImGui.Col_TextDisabled,              0x808080FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_WindowBg,                  0x222222FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_ChildBg,                   0x00000000)
    ImGui.PushStyleColor(ctx, ImGui.Col_PopupBg,                   0x2C2B2BFB)
    ImGui.PushStyleColor(ctx, ImGui.Col_Border,                    0xB6B6B680)
    ImGui.PushStyleColor(ctx, ImGui.Col_BorderShadow,              0x00000000)
    ImGui.PushStyleColor(ctx, ImGui.Col_FrameBg,                   0x6B6B6B86)
    ImGui.PushStyleColor(ctx, ImGui.Col_FrameBgHovered,            0x94949486)
    ImGui.PushStyleColor(ctx, ImGui.Col_FrameBgActive,             0xAAAAAA86)
    ImGui.PushStyleColor(ctx, ImGui.Col_TitleBg,                   0x7CD1E4A8)
    ImGui.PushStyleColor(ctx, ImGui.Col_TitleBgActive,             0x7CD1E4E1)
    ImGui.PushStyleColor(ctx, ImGui.Col_TitleBgCollapsed,          0x7CD1E452)
    ImGui.PushStyleColor(ctx, ImGui.Col_MenuBarBg,                 0x242424FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarBg,               0x05050587)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrab,             0x878787FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrabHovered,      0xB2B2B2FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrabActive,       0xDCDCDCFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_CheckMark,                 0x1BD5FFFE)
    ImGui.PushStyleColor(ctx, ImGui.Col_SliderGrab,                0x23A4C183)
    ImGui.PushStyleColor(ctx, ImGui.Col_SliderGrabActive,          0x23A4C1F1)
    ImGui.PushStyleColor(ctx, ImGui.Col_Button,                    0x23A4C183)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonHovered,             0x23A4C1B4)
    ImGui.PushStyleColor(ctx, ImGui.Col_ButtonActive,              0x23A4C1F1)
    ImGui.PushStyleColor(ctx, ImGui.Col_Header,                    0x23A4C183)
    ImGui.PushStyleColor(ctx, ImGui.Col_HeaderHovered,             0x23A4C1B4)
    ImGui.PushStyleColor(ctx, ImGui.Col_HeaderActive,              0x23A4C1F1)
    ImGui.PushStyleColor(ctx, ImGui.Col_Separator,                 0xD9D9D9C8)
    ImGui.PushStyleColor(ctx, ImGui.Col_SeparatorHovered,          0x4EDCB9FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_SeparatorActive,           0x4EDCB9FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGrip,                0x80DAC466)
    ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGripHovered,         0x80DAC4B0)
    ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGripActive,          0x4EDCB9FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabHovered,                0x4296FACC)
    ImGui.PushStyleColor(ctx, ImGui.Col_Tab,                       0x2E5994DC)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabSelected,               0x3369ADFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabSelectedOverline,       0x4296FAFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmed,                 0x111A26F8)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmedSelected,         0x23436CFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmedSelectedOverline, 0x808080FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_DockingPreview,            0x4296FAB3)
    ImGui.PushStyleColor(ctx, ImGui.Col_DockingEmptyBg,            0x333333FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotLines,                 0x9C9C9CFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotLinesHovered,          0xFF6E59FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotHistogram,             0xE6B300FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_PlotHistogramHovered,      0xFF9900FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableHeaderBg,             0x303033FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableBorderStrong,         0x4F4F59FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableBorderLight,          0x3B3B40FF)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableRowBg,                0x00000000)
    ImGui.PushStyleColor(ctx, ImGui.Col_TableRowBgAlt,             0xFFFFFF0F)
    ImGui.PushStyleColor(ctx, ImGui.Col_TextSelectedBg,            0x42FA8959)
    ImGui.PushStyleColor(ctx, ImGui.Col_DragDropTarget,            0xFFFF00E6)
    ImGui.PushStyleColor(ctx, ImGui.Col_NavHighlight,              0x4296FAFF)
    ImGui.PushStyleColor(ctx, ImGui.Col_NavWindowingHighlight,     0xFFFFFFB3)
    ImGui.PushStyleColor(ctx, ImGui.Col_NavWindowingDimBg,         0xCCCCCC33)
    ImGui.PushStyleColor(ctx, ImGui.Col_ModalWindowDimBg,          0xCCCCCC59)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_Alpha,                       1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_DisabledAlpha,               0.39)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowPadding,               8, 8)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowRounding,              6)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowBorderSize,            1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowMinSize,               32, 32)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowTitleAlign,            0, 0.5)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ChildRounding,               4)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ChildBorderSize,             1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_PopupRounding,               0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_PopupBorderSize,             1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_FramePadding,                4, 3)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_FrameRounding,               0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_FrameBorderSize,             0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ItemSpacing,                 8, 4)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ItemInnerSpacing,            4, 4)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_IndentSpacing,               21)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_CellPadding,                 4, 2)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ScrollbarSize,               14)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ScrollbarRounding,           1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_GrabMinSize,                 12)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_GrabRounding,                0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabRounding,                 0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabBorderSize,               0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabBarBorderSize,            1)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TableAngledHeadersAngle,     0.610865)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_TableAngledHeadersTextAlign, 0.5, 0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_ButtonTextAlign,             0.5, 0.5)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SelectableTextAlign,         0, 0)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextBorderSize,     3)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextAlign,          0, 0.5)
    ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextPadding,        20, 3) 
end

function Clouds.Themes.Dark.Pop(ctx)
    ImGui.PopStyleVar(ctx, 32)
    ImGui.PopStyleColor(ctx, 57)
end




